name: CI/CD Calculadora Java

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Rodar Lint, Testes e Gerar Artefato
      # Valida o padrão de código, roda os testes e cria o JAR
      run: mvn checkstyle:check clean package

    - name: Build Docker Image
      # Cria a imagem Docker usando o arquivo JAR
      run: |
        docker build -t minha-calculadora:latest .
        echo "Imagem Docker criada com sucesso!"